[package]
name = "rust_core"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_core"
crate-type = ["staticlib", "cdylib"]

[dependencies]
ffi-support = "0.4"

[build-dependencies]
cbindgen = "0.26"
