name: Swift Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'macos/**/*.swift'
      - '.github/workflows/swift-tests.yml'
      - '.swiftlint.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'macos/**/*.swift'
      - '.github/workflows/swift-tests.yml'
      - '.swiftlint.yml'

jobs:
  lint:
    name: SwiftLint
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install SwiftLint
        run: brew install swiftlint
      
      - name: Run SwiftLint
        run: swiftlint lint --strict --reporter github-actions-logging
        continue-on-error: false

  test:
    name: Test Swift Code
    runs-on: macos-latest
    
    strategy:
      matrix:
        xcode: ['15.2']
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
      
      - name: Show Xcode version
        run: xcodebuild -version
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin
      
      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            rust-core/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      
      - name: Build Rust core
        run: |
          cd rust-core
          cargo build
      
      - name: Run tests
        run: |
          xcodebuild test \
            -project macos/LindosTrayApp/LindosTrayApp.xcodeproj \
            -scheme LindosTrayApp \
            -destination 'platform=macOS' \
            -enableCodeCoverage YES \
            | xcpretty --test --color
        continue-on-error: false
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-xcode-${{ matrix.xcode }}
          path: |
            ~/Library/Developer/Xcode/DerivedData/*/Logs/Test/*.xcresult
          retention-days: 7

  build:
    name: Build macOS App
    runs-on: macos-latest
    needs: [lint, test]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin
      
      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            rust-core/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      
      - name: Build macOS app
        run: ./scripts/build_macos.sh debug
      
      - name: Verify build artifacts
        run: |
          ls -la build/Debug/
          file build/Debug/LindosTrayApp.app/Contents/MacOS/LindosTrayApp
